"""
reports.py — printable HTML report cards (player season card + single-game recap).

Same zero-dependency, print-to-PDF approach as the scout sheet: pure HTML/CSS
strings a page hands to st.download_button. Assembles existing engines (player
stat table, badges, trends, fouls, gameflow, team boxes) — no new data.
Streamlit-free.
"""
from __future__ import annotations

import datetime
import html as _html

from database.db import query
import helpers.stats as S
import helpers.player_ratings as PR
import helpers.team_analytics as TA
import helpers.gameflow as GF
import helpers.trends as TRD
import helpers.fouls as FL
import helpers.badges as BG

e = _html.escape

_CSS = """
*{box-sizing:border-box}
html{-webkit-print-color-adjust:exact;print-color-adjust:exact}
body{font-family:'Segoe UI',-apple-system,Arial,sans-serif;color:#16202c;margin:0;
  font-size:13px;line-height:1.45;background:#fff}
.wrap{max-width:920px;margin:0 auto;padding:0 26px 30px}
.band{background:linear-gradient(120deg,#0d1117 0%,#1b2433 60%,#243049 100%);
  color:#f0f6fc;padding:20px 26px;border-bottom:5px solid #f0a500;margin-bottom:16px}
.band .mark{font-size:10px;letter-spacing:3px;text-transform:uppercase;color:#f0a500;font-weight:800}
.band h1{margin:4px 0 2px;font-size:25px}
.band .meta{color:#aeb9c7;font-size:12.5px}
.chips{margin-top:10px}
.chip{display:inline-block;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.16);
  border-radius:999px;padding:4px 11px;margin:3px 6px 0 0;font-size:11.5px;color:#dbe4ee}
.chip b{color:#fff}
h2{font-size:13px;text-transform:uppercase;letter-spacing:1.4px;color:#0d1117;
  border-left:4px solid #f0a500;padding-left:9px;margin:18px 0 9px}
table{border-collapse:collapse;width:100%;font-size:12.5px}
th{text-align:left;font-size:10.5px;letter-spacing:.6px;text-transform:uppercase;color:#5b6675;
  border-bottom:2px solid #16202c;padding:6px 8px}
td{padding:5px 8px;border-bottom:1px solid #e7ebf0}
tr:nth-child(even) td{background:#f7f9fb}
.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
table.kpis{width:100%;border-collapse:separate;border-spacing:5px 0;margin:6px 0 4px}
td.kpi{background:#f7f9fb;border:1px solid #e7ebf0;border-radius:9px;
  padding:9px 6px;text-align:center}
.kpi .v{font-size:20px;font-weight:800;color:#16202c;font-variant-numeric:tabular-nums}
.kpi .l{font-size:9.5px;text-transform:uppercase;letter-spacing:.5px;color:#5b6675}
.bdg{display:inline-block;font-size:10px;font-weight:700;color:#6b4e00;background:#fff3d6;
  border:1px solid #f0d692;border-radius:5px;padding:2px 7px;margin:3px 5px 0 0}
.foot{margin-top:20px;padding-top:10px;border-top:1px solid #e7ebf0;color:#8a94a2;font-size:11px}
@media print{.break{page-break-before:always}}
"""


def _today():
    try:
        d = datetime.date.today()
        return f"{d.strftime('%b')} {d.day}, {d.year}"
    except Exception:
        return ""


def _doc(title, body):
    return (f"<!doctype html><html lang='en'><head><meta charset='utf-8'>"
            f"<meta name='viewport' content='width=device-width, initial-scale=1'>"
            f"<title>{e(title)}</title><style>{_CSS}</style></head><body>{body}"
            f"<div class='wrap'><div class='foot'>Generated by Analytics Hub"
            f"{(' · ' + _today()) if _today() else ''}.</div></div></body></html>")


def _kpi(label, value):
    # A table cell, not a flex child — xhtml2pdf (the PDF engine) has no flexbox.
    return f"<td class='kpi'><div class='v'>{value}</div><div class='l'>{e(label)}</div></td>"


# ── per-player season report card ────────────────────────────────────────────────
def player_card_html(player_id, gender=None, table=None):
    if table is None:
        table = PR.player_stat_table(gender=gender, min_games=1)
    r = table.get(player_id)
    if not r:
        return _doc("Player card", "<div class='wrap'>Player not found.</div>")
    badges = BG.award_badges(table).get(player_id, [])
    log = TRD.player_game_log(player_id)
    highs = TRD.season_highs(log)
    ff = FL.player_foul_ft().get(player_id, {})

    def g(k, f="{:.1f}"):
        v = r.get(k)
        return f.format(v) if v is not None else "—"

    band = (
        f"<div class='band'><div class='mark'>Analytics Hub · Player Card</div>"
        f"<h1>#{r.get('number','')} {e(r['name'])}</h1>"
        f"<div class='meta'>{e(r['team'])} · {e(r.get('class','N/A'))} · "
        f"{r.get('GP',0)} games</div>"
        f"<div class='chips'>"
        f"<span class='chip'><b>{g('OVERALL','{:.0f}')}</b> OVR</span>"
        f"<span class='chip'><b>{g('OFFENSE','{:.0f}')}</b> OFF</span>"
        f"<span class='chip'><b>{g('DEFENSE','{:.0f}')}</b> DEF</span>"
        f"<span class='chip'><b>{g('PLAYMAKING','{:.0f}')}</b> PLAY</span>"
        f"<span class='chip'><b>{g('REBOUNDING','{:.0f}')}</b> REB</span></div></div>")

    kpis = "".join([
        _kpi("PPG", g("PPG")), _kpi("RPG", g("RPG")), _kpi("APG", g("APG")),
        _kpi("SPG", g("SPG")), _kpi("BPG", g("BPG")), _kpi("FG%", g("FG%", "{:.0f}")),
        _kpi("3P%", g("3P%", "{:.0f}")), _kpi("TS%", g("TS%", "{:.0f}")),
        _kpi("USG%", g("USG%", "{:.0f}")),
    ])

    bdg = "".join(f"<span class='bdg'>{e(b['emoji'])} {e(b['name'])}</span>"
                  for b in badges[:8]) or "<span style='color:#8a94a2'>—</span>"

    hrows = ""
    for k, lbl in TRD.HIGH_KEYS:
        h = highs.get(k)
        if h:
            hrows += (f"<tr><td>{e(lbl)}</td><td class='num'>{h['value']}</td>"
                      f"<td>{e(h['opp'])}</td><td class='num'>{e(h['date'])}</td></tr>")

    ftline = ""
    if ff:
        ftline = (f"<table class='kpis'><tr>{_kpi('Fouls drawn', ff.get('drawn',0))}"
                  f"{_kpi('Fouls', ff.get('PF',0))}"
                  f"{_kpi('FT', str(ff.get('FTM',0))+'/'+str(ff.get('FTA',0)))}"
                  f"{_kpi('FT%', ('%.0f%%'%ff['FT%']) if ff.get('FTA') else '—')}</tr></table>")

    lrows = ""
    for game in log[-15:][::-1]:
        b = game["box"]
        lrows += (f"<tr><td class='num'>{e(game['date'])}</td><td>{e(game['opp'])}</td>"
                  f"<td class='num'>{b.get('PTS',0)}</td><td class='num'>{b.get('TRB',0)}</td>"
                  f"<td class='num'>{b.get('AST',0)}</td><td class='num'>{b.get('STL',0)}</td>"
                  f"<td class='num'>{b.get('BLK',0)}</td>"
                  f"<td class='num'>{b.get('FGM',0)}/{b.get('FGA',0)}</td>"
                  f"<td class='num'>{b.get('FTM',0)}/{b.get('FTA',0)}</td></tr>")

    body = (
        f"{band}<div class='wrap'>"
        f"<h2>Season averages</h2><table class='kpis'><tr>{kpis}</tr></table>"
        f"<h2>Badges</h2><div>{bdg}</div>"
        + (f"<h2>Fouls &amp; free throws</h2>{ftline}" if ff else "")
        + (f"<h2>Season highs</h2><table><tr><th>Stat</th><th class='num'>High</th>"
           f"<th>vs</th><th class='num'>Date</th></tr>{hrows}</table>" if hrows else "")
        + (f"<h2>Recent games</h2><table><tr><th>Date</th><th>Opp</th>"
           f"<th class='num'>PTS</th><th class='num'>REB</th><th class='num'>AST</th>"
           f"<th class='num'>STL</th><th class='num'>BLK</th><th class='num'>FG</th>"
           f"<th class='num'>FT</th></tr>{lrows}</table>" if lrows else "")
        + "</div>")
    return _doc(f"Player card · {r['name']}", body)


# ── single-game recap ────────────────────────────────────────────────────────────
def game_recap_html(game_id):
    g = query("""SELECT g.id, g.date, g.team1_id, g.team2_id, g.home_score,
                        g.away_score, t1.name n1, t2.name n2
                 FROM games g JOIN teams t1 ON t1.id=g.team1_id
                              JOIN teams t2 ON t2.id=g.team2_id WHERE g.id=?""",
              (game_id,))
    if not g:
        return _doc("Game recap", "<div class='wrap'>Game not found.</div>")
    g = g[0]
    t1id, t2id = g["team1_id"], g["team2_id"]
    events = S.fetch_events([game_id])
    tb, ob = TA.team_and_opp_box(t1id, [game_id], events=events)
    sb = GF.scoring_buckets([game_id], events=events)
    meta = {r["id"]: r for r in query("SELECT id, name, number, team_id FROM players")}
    boxes = {pid: S.finalize_box(b)
             for pid, b in S.aggregate_player_boxes([game_id], events=events).items()}

    h1 = tb.get("PTS", 0)
    h2 = ob.get("PTS", 0)

    def _tcol(box, label):
        rows = (("PTS", box.get("PTS", 0)), ("FG", f"{box.get('FGM',0)}/{box.get('FGA',0)}"),
                ("3P", f"{box.get('3PM',0)}/{box.get('3PA',0)}"),
                ("FT", f"{box.get('FTM',0)}/{box.get('FTA',0)}"),
                ("REB", box.get("TRB", 0)), ("OREB", box.get("OREB", 0)),
                ("AST", box.get("AST", 0)), ("STL", box.get("STL", 0)),
                ("BLK", box.get("BLK", 0)), ("TOV", box.get("TOV", 0)),
                ("PF", box.get("PF", 0)))
        return "".join(f"<tr><td>{k}</td><td class='num'>{v}</td></tr>" for k, v in rows)

    bk1, bk2 = sb.get(t1id, {}), sb.get(t2id, {})
    bkrows = ""
    for lbl, key in (("Paint", "paint"), ("2nd chance", "second_chance"),
                     ("Off turnovers", "off_turnover"), ("Fast break", "fast_break"),
                     ("Bench", "bench")):
        bkrows += (f"<tr><td class='num'>{bk1.get(key,0)}</td><td>{e(lbl)}</td>"
                   f"<td class='num'>{bk2.get(key,0)}</td></tr>")

    def _pbox(team_id):
        rs = sorted([(pid, b) for pid, b in boxes.items()
                     if meta.get(pid, {}).get("team_id") == team_id],
                    key=lambda kb: -kb[1].get("PTS", 0))
        out = ""
        for pid, b in rs:
            m = meta.get(pid, {})
            out += (f"<tr><td>#{m.get('number','')} {e(m.get('name','?'))}</td>"
                    f"<td class='num'>{b.get('PTS',0)}</td>"
                    f"<td class='num'>{b.get('TRB',0)}</td><td class='num'>{b.get('AST',0)}</td>"
                    f"<td class='num'>{b.get('STL',0)}</td><td class='num'>{b.get('BLK',0)}</td>"
                    f"<td class='num'>{b.get('FGM',0)}/{b.get('FGA',0)}</td>"
                    f"<td class='num'>{b.get('FTM',0)}/{b.get('FTA',0)}</td></tr>")
        return out

    won1 = h1 >= h2
    band = (
        f"<div class='band'><div class='mark'>Analytics Hub · Game Recap</div>"
        f"<h1>{e(g['n1'])} {h1} &ndash; {h2} {e(g['n2'])}</h1>"
        f"<div class='meta'>{e(g['date'] or '')} · "
        f"{e(g['n1'] if won1 else g['n2'])} win</div></div>")

    def _phdr():
        return ("<tr><th>Player</th><th class='num'>PTS</th><th class='num'>REB</th>"
                "<th class='num'>AST</th><th class='num'>STL</th><th class='num'>BLK</th>"
                "<th class='num'>FG</th><th class='num'>FT</th></tr>")

    body = (
        f"{band}<div class='wrap'>"
        f"<h2>Team totals</h2>"
        f"<table style='width:100%;border-collapse:separate;border-spacing:12px 0'><tr>"
        f"<td style='width:50%;vertical-align:top;border:none;padding:0'>"
        f"<table><tr><th>{e(g['n1'])}</th><th></th></tr>{_tcol(tb,'')}</table></td>"
        f"<td style='width:50%;vertical-align:top;border:none;padding:0'>"
        f"<table><tr><th>{e(g['n2'])}</th><th></th></tr>{_tcol(ob,'')}</table></td>"
        f"</tr></table>"
        f"<h2>Scoring breakdown</h2><table>"
        f"<tr><th class='num'>{e(g['n1'])}</th><th></th><th class='num'>{e(g['n2'])}</th></tr>"
        f"{bkrows}</table>"
        f"<h2>{e(g['n1'])} — box score</h2><table>{_phdr()}{_pbox(t1id)}</table>"
        f"<h2 class='break'>{e(g['n2'])} — box score</h2><table>{_phdr()}{_pbox(t2id)}</table>"
        f"</div>")
    return _doc(f"Recap · {g['n1']} vs {g['n2']}", body)
